### ISSUE TITLE
Tarea

### ISSUE THREAD

**Issue by GuillermoPellegrini1** [Ana-Clara-M/ingeniera-historia#2]

**Comment by Ana-Clara-M** [comment]
Introducción a la Ingeniería

Objetivos de aprendizaje:

Dominar el texto colaborativo
Comprender la diferencia entre ciencia y tecnología
Timeline


Actividad de Aprendizaje 1
Defina con sus propias palabras ¿Qué es ingeniería?

La ingeniería es un campo disciplinar que ha crecido casi con la humanidad a lo largo de la historia hemos podido encontrar restos y rasgos de ingeniería que son anteriores a la aparición de la escritura así lo que conocemos como Edad de Piedra, edad de bronce, era del cobre, edad del hierro, nos refleja cómo era la ingeniería en esas civilizaciones aún cuando no tenemos registro escrito de lo que sucedía en ellas pero podemos deducir algunas de las técnicas y estrategias que se llevaron a cabo a partir de la ingeniería. Además la Ingeniería ha ido desarrollándose a lo largo del tiempo, y ha dado lugar a diversos campos disciplinares, como la ingeniería civil, mecánica, eléctrica entre otras. En la actualidad la ingeniería sigue siendo un campo en constante evolución; el cual es fundamental para el desarrollo de nuevas tecnologías y soluciones a problemas complejos en distintas áreas, como la medicina, la energía, la informática, el transporte, entre otras.

Actividad de Aprendizaje 2
Defina que es Ciencia
La ciencia son métodos sistemáticos y lógicos que se utilizan para descubrir y comprender la realidad a través de observaciones, hipótesis, experiencias, mediciones y análisis. Su finalidad es adquirir conocimientos verificables y comprobables acerca de amplios temas como: el universo, la naturaleza, o el ser humano, con el objetivo de formular teorías y leyes generales que expliquen cómo funcionan, por qué existen y cómo interaccionan. La ciencia es una herramienta efectiva para entender el mundo que nos rodea y tomar decisiones informadas.

Actividad de Aprendizaje 3
Haga un resumen de dos carillas con los principales avances de la ingeniería de cada civilización

Estos son algunos de los principales avances de la ingeniería en cada una de estas civilizaciones
 Civilización Egipcia (c. 3000 a.C. - c. 30 a.C.)
se caracterizó por la construcción duradera de majestuosas pirámides y templos, además de sistemas de irrigación y obras hidráulicas.
Diseño y construcción de  pirámides, mediante la utilización de grandes bloques de piedra. Empleando rampas y poleas para transportar los bloques y colocarlos en la posición adecuada.
La construcción de los canales de irrigación y los diques, que permitían el control de las inundaciones del Nilo y el aprovechamiento de sus aguas para la agricultura.
La creación de un sistema de escritura jeroglífica, que permitía registrar y transmitir la información técnica y científica de la época.


Civilización Romana (c. 753 a.C. - 476 d.C.)
Estuvo marcada por el dominio de la arquitectura y la construcción de grandes estructuras, así como avances en la matemática y la mecánica. 
Construcción de grandes acueductos y sistemas de suministro de agua, (acueducto de Segovia o el Acqua Vergine)
Desarrollo de las matemáticas, con importantes avances en la geometría, la trigonometría y la aritmética. Euclides, Arquímedes y Pitágoras, algunos de los más notables matemáticos.
La invención de la rueda de molino, el tornillo de Arquímedes, el reloj de agua y la Catapulta que posibilitaron mejoras en la productividad y la eficiencia de la industria y el comercio.


Civilización China (c. 2100 a.C. - presente)
Se caracterizó por la construcción de grandes y complejas obras públicas y sistemas de transporte. 
La construcción de la Gran Muralla de China, uno de los proyectos de ingeniería más grandes. Se construyeron numerosos puentes de piedra y arcos para carruajes y barcos.
El sistema de transporte Grand Canal, una de las mayores obras de ingeniería de la época, permitía el transporte de bienes y personas desde el norte hasta el sur de China. .
Descubrimiento y uso de la pólvora, revolucionó la guerra y permitió el desarrollo de armas como el cañón y la ballesta.


Civilización Islámica (siglos VII al XV)
Se centró en la construcción de grandes obras públicas y el desarrollo de avances en matemáticas y astronomía. 
Diseño y construcción de mezquitas, caracterizadas por sus altos minaretes y decoración.
Invención del astrolabio, medidor de ángulos utilizado para determinar la posición de los astros en el cielo, esto permitió avances significativos en la navegación y la determinación de la hora.
Desarrollo de la geometría, llevado a cabo por matemáticos como Al-Khwarizmi y Omar Khayyam, que establecieron las bases del álgebra y la trigonometría modernas. 

Civilización Maya (c. 2000 a.C. - c. 1500 d.C.)
Se destacó por su avanzado conocimiento en la ingeniería agrícola y construcción de estructuras arquitectónicas. 
Sistema de terrazas, permitía el cultivo en pendientes y protegía los suelos de la erosión provocada por la lluvia y el viento, se utilizaba en la construcción de terrazas de cultivo .
Uso de canales de riego y sistemas hidráulicos que permitían un adecuado suministro de agua para la agricultura y el consumo humano. Además, crearon depósitos y embalses subterráneos para almacenar agua durante la temporada seca.
Desarrollaron técnicas de construcción sin el uso del mortero, y esto permitió la construcción de grandes edificios y monumentos con bloques de piedra. 
Su conocimiento en astronomía y matemáticas contribuyó al desarrollo de un preciso calendario de 18 meses de 20 días cada uno, además del uso del número cero y la creación de la base 20 en su sistema numérico.




Interpretación y resumen de texto

Actividad de Aprendizaje 4
Resume este texto en 200 palabras

Entre 1500 y 1750, se separaron la ingeniería civil y la militar. La ingeniería naval se creció gracias a los viajes interoceánicos. La ingeniería mecánica se fortaleció con la creación de instrumentos como el telescopio y la bomba neumática. Por su parte la imprenta comercial contribuyó a la difusión del conocimiento ingenieril. Destacadas figuras como Leonardo da Vinci, Galileo Galilei, Simón Stevin, Fermat, Descartes, Jean Baptiste y Gorgius Agrícola realizaron importantes descubrimientos y aportes.
Entre 1750 y 1900, se produjo la Revolución Industrial, caracterizada por avances clave en ingeniería. Se descubrió la transformación de la energía calorífica en energía mecánica y se comprendió la atmósfera y la presión atmosférica. Se inventó la máquina de vapor que impulsó la Revolución Industrial, seguido del surgimiento de las locomotoras y el uso del carbón como combustible. Hubo aumentos en la productividad y la especialización laboral, pero también aparecieron grandes problemas ambientales.
En el siglo XIX, se patentó el motor de combustión interna y se formularon principios sobre la inducción de corriente eléctrica. Se inventó el telégrafo que dio lugar a la ingeniería de las telecomunicaciones. La etapa también estuvo marcada por la invención del foco una mayor demanda de energía eléctrica, tanto de las personas como de la industria.
Todos estos avances sentaron las bases para los grandes progresos del siglo XX.


Actividad de Aprendizaje 5
Menciona el invento que dio origen a la revolución industrializadas

Uno de los inventos que dió lugar a la revolución industrial fue a principios de siglo XVIII, Thomas New Comen construyó la primera máquina de vapor funcional de la historia, y años después James Watt la mejoró.

Actividad de Aprendizaje 6
¿Que falacia encierra el texto?

Actividad de Aprendizaje 7
¿Cuándo se concibió la Ingeniería Industrial? ¿Cuándo se concibió la ingeniería mecatrónica?

La Ingeniería Industrial se concibió con la Revolución Industrial del siglo XVIII en Inglaterra. A medida que los procesos de manufactura y producción se volvieron más complejos y automatizados, se hizo necesaria la creación de una nueva disciplina que aborda los desafíos de gestión y optimización de estos procesos. 

La ingeniería mecatrónica se concibió a finales de la década de los sesenta con la integración de las ingenierías mecánica,  electrónica, y de control. Surge como respuesta a la necesidad de formar ingenieros capacitados para diseñar y desarrollar sistemas donde se combinan procesos mecánicos con procesos electrónicos y de control en un solo sistema integrado. Corvintendose en  una disciplina vital para la automatización y la robótica.
